jobs:
  build:
    docker:
      -
        image: "circleci/buildpack-deps:stretch"
    environment:
      IMAGE_NAME: tamaslakatos/building-on-ci
    steps:
      - checkout
      - setup_remote_docker
      -
        run:
          command: "docker build -t $IMAGE_NAME:latest ."
          name: "Build Docker image"
version: 2
workflows:
  build-master:
    jobs:
      -
        build:
          filters:
            branches:
              only: master
  version: 2

